import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";

export default function TermsPage() {
  return (
    <div className="auth-shell">
      <div className="mx-auto max-w-2xl space-y-4 px-4 py-10">
        <BrandLogo size={32} />
        <h1 className="text-3xl font-semibold tracking-tight">Terms</h1>
        <p className="text-sm text-neutral-600">
          LeadDoc provides an AI chat widget and lead CRM for dental practices on a monthly subscription. The widget is
          available while the clinic&apos;s subscription is active or trialing, unless a platform admin has allowed an
          exception.
        </p>
        <p className="text-sm text-neutral-600">
          Chat replies are generated by a language model. They are not clinical advice and must not be treated as a
          diagnosis. Clinics are responsible for the FAQs, prompts, and follow-up they configure, and for how they use
          visitor data.
        </p>
        <p className="text-sm text-neutral-600">
          You can cancel from Settings using the Stripe billing portal. Fees already billed are not refunded except where
          required by law.
        </p>
        <p className="text-sm">
          <Link href="/" className="font-semibold underline">
            Home
          </Link>
        </p>
      </div>
    </div>
  );
}
