import { NextResponse } from "next/server";
import {
  addKnowledgeAction,
  addKnowledgePackAction,
  addOptionAction,
  adminAddSupportNoteAction,
  adminChargeAction,
  adminCreateChatbotAction,
  adminCreateClinicAction,
  adminCreateStripeSubAction,
  adminLinkStripeAction,
  adminSavePlanAction,
  adminToggleWidgetExceptionAction,
  createChatbotAction,
  deleteKnowledgeAction,
  deleteOptionAction,
  exitImpersonateAction,
  impersonateAction,
  inviteStaffAction,
  logoutAction,
  markNotificationsReadAction,
  saveBrandingAction,
  saveChatbotAction,
  signupAction,
  startCheckoutAction,
  updateLeadAction,
  createLeadTaskAction,
  completeLeadTaskAction,
  deleteLeadsAction,
  patchLeadInlineAction,
  createPipelineAction,
  updatePipelineAction,
  addPipelineStageAction,
  updatePipelineStageAction,
  deletePipelineStageAction,
  deletePipelineAction,
  addLeadNoteAction,
  addLeadRecallAction,
  completeLeadRecallAction,
  updateOptionAction,
} from "@/lib/actions";

const handlers: Record<string, (formData: FormData) => Promise<void>> = {
  signup: signupAction,
  logout: () => logoutAction(),
  checkout: () => startCheckoutAction(),
  saveChatbot: saveChatbotAction,
  createChatbot: createChatbotAction,
  addOption: addOptionAction,
  updateOption: updateOptionAction,
  deleteOption: deleteOptionAction,
  addKnowledge: addKnowledgeAction,
  addKnowledgePack: addKnowledgePackAction,
  deleteKnowledge: deleteKnowledgeAction,
  saveBranding: saveBrandingAction,
  inviteStaff: inviteStaffAction,
  updateLead: updateLeadAction,
  createLeadTask: createLeadTaskAction,
  completeLeadTask: completeLeadTaskAction,
  deleteLeads: deleteLeadsAction,
  patchLeadInline: patchLeadInlineAction,
  createPipeline: createPipelineAction,
  updatePipeline: updatePipelineAction,
  addPipelineStage: addPipelineStageAction,
  updatePipelineStage: updatePipelineStageAction,
  deletePipelineStage: deletePipelineStageAction,
  deletePipeline: deletePipelineAction,
  addLeadNote: addLeadNoteAction,
  addLeadRecall: addLeadRecallAction,
  completeLeadRecall: completeLeadRecallAction,
  markNotificationsRead: () => markNotificationsReadAction(),
  adminCreateClinic: adminCreateClinicAction,
  impersonate: impersonateAction,
  exitImpersonate: () => exitImpersonateAction(),
  adminLinkStripe: adminLinkStripeAction,
  adminCreateStripeSub: adminCreateStripeSubAction,
  adminCharge: adminChargeAction,
  adminSavePlan: adminSavePlanAction,
  adminAddSupportNote: adminAddSupportNoteAction,
  adminToggleWidgetException: adminToggleWidgetExceptionAction,
  adminCreateChatbot: adminCreateChatbotAction,
};

export async function POST(request: Request, ctx: { params: Promise<{ name: string }> }) {
  const { name } = await ctx.params;
  const formData = await request.formData();
  const handler = handlers[name];
  if (!handler) {
    return NextResponse.json({ error: "Unknown form" }, { status: 404 });
  }
  await handler(formData);
  return NextResponse.json({ ok: true });
}
